server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/smartledger_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.flyway.enabled=false

app.jwt.secret=paisanest_secret_key_minimum_32_characters_long
app.jwt.expiration=86400000

app.groq.api-key=${APP_GROQ_API_KEY:placeholder}
app.razorpay.key-id=${APP_RAZORPAY_KEY_ID:placeholder}
app.razorpay.key-secret=${APP_RAZORPAY_KEY_SECRET:placeholder}
app.trial.hours=52

spring.mail.host=${SPRING_MAIL_HOST:smtp-relay.brevo.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.cors.allowed-origins=*